### ISSUE TITLE
Scrolling is very awkward

### ISSUE THREAD

**Issue by madprops** [PMunch/nim-playground-frontend#11]
I'm not sure what happens but scrolling is not smooth. Sometimes it just jumps around, or gets stuck. If I zoom a bit too much it shows double scrollbars. Maybe something could be improved there?

**Comment by PMunch** [comment]
I'm planning to completely rewrite the UI so it will be easier to add new features to it. Will try to make sure the new one works better. Out of curiosity since I haven't seen these issues on either my phone nor my computer, what browser/platform are you on?

**Comment by madprops** [comment]
Firefox on Linux. 1920x1200 monitor, I tend to zoom-in on pages.

**Comment by PMunch** [comment]
Yeah I use Vivaldi on Linux on a 3840x2160 monitor. Have it set to default zoom to 120%
