### ISSUE TITLE
Font size input field is highlighted in red by default, showing that its value is invalid

### ISSUE THREAD

**Issue by roryokane** [PMunch/nim-playground-frontend#14]
## Problem

When I load https://play.nim-lang.org/ in Firefox, the “Font size” input field is shown in red:

<img width="565" alt="settings with “Font size” field in red" src="https://user-images.githubusercontent.com/79168/75619984-1de13b00-5b51-11ea-9a81-1f2615a494de.png">

Hovering over the field reveals a tooltip saying “Please select a valid value.”:

<img width="565" alt="“Font size” error tooltip starting with “Please select a valid value.”" src="https://user-images.githubusercontent.com/79168/75620086-2a19c800-5b52-11ea-8563-e90b056ff79e.png">

In Google Chrome, I don’t see the red highlight, but I still see the tooltip:

<img width="565" alt="the field and its tooltip in Chrome" src="https://user-images.githubusercontent.com/79168/75620133-c80d9280-5b52-11ea-81ac-11c3dc96dcf3.png">

The red highlight and the tooltip are a distraction from the user’s main task of trying out Nim code.

## Solution

The form should be initialized in a valid state so that the “Font size” text field looks and acts normal.

The validation happens because of the [`step`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-step) attribute of that `input` element:

~~~html
<input id="fontsize" type="number" min="8" max="50" step="2" required="required">
~~~

That `input` field is defined on [line 250 in `frontend.nim`](https://github.com/PMunch/nim-playground-frontend/blob/00444ba34c8c81b0b6ddda8162299773d10c2f8c/frontend.nim#L250).

I suggest one of the following fixes:

- Change `step` to 1. As a side effect, this will cause the up/down buttons in the field to change the number by 1 instead of 2.
- Change the default font size to 14.

Note that adding [`novalidate`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-novalidate) to the `input`’s surrounding `form` element will not disable this validation – `novalidate` only affects validation upon submitting the form, not displayed errors.

**Comment by PMunch** [comment]
The `step="2"` was done because I didn't feel anyone would need that fine control. But I'm fine with either of the changes you proposed, please create a PR to fix it :)
