### ISSUE TITLE
🐞: Blinking cursor does not sync with the change font size

### ISSUE THREAD

**Issue by joe733** [PMunch/nim-playground-frontend#16]
Hi, I do not know if you have already noticed this but when I increase the font size, the cursor remains in the same size unless I start to type (feels awkward at first)
![Annotation 2020-05-10 122715](https://user-images.githubusercontent.com/38415384/81492945-da761c00-92b9-11ea-9778-cc74898afb42.png)
That cursor in the circle after `in` is actually at the last line because when I type the cursor automatically moves to the last line and does the editing.

**Comment by PMunch** [comment]
This is unfortunately a bug in [CodeMirror](https://github.com/codemirror/CodeMirror) which is what the playground uses for the edit area. I suggest you forward this bug report to their repository, I can confirm that I'm seeing the same issue as well.

**Comment by joe733** [comment]
@PMunch could this be a solution: https://github.com/codemirror/CodeMirror/issues/6266#issuecomment-626323310?

**Comment by PMunch** [comment]
Ah, indeed that could be a solution!
