### ISSUE TITLE
provide a JSON API

### ISSUE THREAD

**Issue by timotheecour** [PMunch/nim-playground-frontend#18]
## allow encoding code + compilation command/options as json in httprequest body
this feature will allow nim's runnableExamples to have a clickable link that, when clicked, will open nim playground with the code pre-populated from that runnableExample

## API: input json (compilation command + input as text) => output as json (stderr, stdout, exitCode)
this will allow implementing what's done in D: https://dlang.org/phobos/std_datetime.html

![image](https://user-images.githubusercontent.com/2194784/82162631-df5b4280-985a-11ea-85fa-ec51f66a34d4.png)

(it can have a "powered by https://play.nim-lang.org/ logo)

**Comment by PMunch** [comment]
This is more of a back-end issue than a front-end one, and the back-end has had this feature for years already, it's what `!eval` from the IRC bot uses (and the front-end itself for that matter).

**Comment by timotheecour** [comment]
excellent thanks!
