### ISSUE TITLE
Link to repos/versions the currently running playground is based on

### ISSUE THREAD

**Issue by sschwarzer** [PMunch/nim-playground-frontend#2]
My confusion about which software was used for the playground (see https://github.com/zacharycarter/nim-playground/issues/4 / https://github.com/zacharycarter/nim-playground/pull/5 vs. https://github.com/PMunch/nim-playground-frontend/issues/1 ) could have been avoided if there were links on the playground frontend to the repositories that are used for the playground.

I think it could also make sense to put the revisions on the playground page the playground is based on. This would make it possible to check what has changed in the repositories since the deployment, which would help find out whether a certain problem has already been fixed with respect to the deployed playground.

**Comment by PMunch** [comment]
I try to keep the playground always up to date with the master branch of this repository, so revisions doesn't really make much sense. But I'll be sure to add a link to this repository on the playground page. This is in fact something I thought about doing from the start, but haven't quite figured out where to put the notice..

**Comment by sschwarzer** [comment]
I guess a link put anywhere is better than no link at all. ;-)

Maybe put the link a bit below the output? If the link is some bright color on black (as typical for the current playground), it should be visible enough.

Oops, looks like you put a link there already? :) But it took a while until I saw it. A little bit more contrast wouldn't hurt I think.

**Comment by PMunch** [comment]
Since the link is now on the page and it's always synced to the master branch I'll consider this resolved :)
