### ISSUE TITLE
Double scrollbars

### ISSUE THREAD

**Issue by madprops** [PMunch/nim-playground-frontend#23]
![nimscrollbars](https://user-images.githubusercontent.com/206498/131310137-dd142e47-0488-4d88-bc3c-0e71a5b8c45b.jpg)

This happens on Firefox as well as on Vivaldi (chrome based). 

A a second overflow occurs, one is the whole page, one is the code container.

This makes it harder to scroll naturally, as it gets in the way.

I think there should only be 1 scrollbar to deal with.

To see this, copy some long text until it overflows, then focus the code area, zoom and scroll around.

**Comment by PMunch** [comment]
Yeah this is a known issue. The entire website is due for a design refresh, but I simply don't have time to do that right now. If anyone else wants to contribute to that it would be great!
