### ISSUE TITLE
Font Size Too Small

### ISSUE THREAD

**Issue by madranet** [PMunch/nim-playground-frontend#3]
I know my old eyes aren't as young as they used to be, but any chance of adding some font-size control to the Playground? On my 11" laptop, it's positively microscopic.

![SS 2019-09-24 at 13 21 28](https://user-images.githubusercontent.com/669658/65511237-9e2eb080-dece-11e9-8078-401dc8b7374f.png)

**Comment by PMunch** [comment]
Is it specifically the text in the editor you want to make bigger? Or all the text?

**Comment by madranet** [comment]
It's the text in the editor.

**Comment by PMunch** [comment]
Added an options bar now that includes font size and compilation target
