### ISSUE TITLE
Seems to have stopped working

### ISSUE THREAD

**Issue by michaelsbradleyjr** [PMunch/nim-playground-frontend#32]
Clicking `Run` with any code in the input section results in `Unable to open output log`:

![image](https://user-images.githubusercontent.com/194260/172716271-13cee2fe-7276-43db-94cf-f273379a1930.png)

I tried in several different browsers and different devices on different networks (wifi, cell) and it was the same situation in all cases.

**Comment by PMunch** [comment]
This is a deployment issue, the disk ran out of space. I'll fix it tomorrow.

**Comment by PMunch** [comment]
Did some maintenance while I was at it. The playground is back up now
