### ISSUE TITLE
play.nim-lang.org fails to load, is it still being maintained?

### ISSUE THREAD

**Issue by noahehall** [PMunch/nim-playground-frontend#34]
play.nim-lang.org throws bad gateway

![image](https://user-images.githubusercontent.com/10324554/222980255-4439bab1-b9d5-43fa-b64e-90f989bcea9b.png)

**Comment by PMunch** [comment]
Yes, the playground is still being maintained. It's just running on a really crummy VPS which means that it crashes quite a bit. I'll probably delete a couple of the supported versions, that should at least help
