### ISSUE TITLE
/usercode/in.nim(2, 8) Error: cannot open file: glm

### ISSUE THREAD

**Issue by adammaj1** [PMunch/nim-playground-frontend#37]
I have a nim code from [what-every-coder-should-know-about-gamma](https://blog.johnnovak.net/2016/09/21/what-every-coder-should-know-about-gamma/). WHen I try to run it in the playgraund it gives an error : 

/usercode/in.nim(2, 8) Error: cannot open file: glm

The glm module is in [github](https://github.com/stavenko/nim-glm)

How can I solve it ?

**Comment by PMunch** [comment]
Unfortunately the answer to this would be to install Nim properly on your machine. The playground is just intended to let people try out the features of the language or play around with simple scripts. It does have a [list of packages installed](https://github.com/PMunch/nim-playground/blob/master/docker/packages.nimble) but GLM isn't one of those. The code executing on the playground doesn't have any internet either, so there'd be no way to install new packages on the fly either.
