### ISSUE TITLE
Nimpy installed on server

### ISSUE THREAD

**Issue by juancarlospaco** [PMunch/nim-playground-frontend#4]
Can we have nimpy installed on the server :grey_question: 

I always want to try/share Nim snippets quickly and have to edit to remove/add the `{.exportpy.}` and other edits to make it work with the Nimpy code.

No code change would be required, just install Nimpy on the server, not more support than that would be required.

**Comment by PMunch** [comment]
Well it's not quite that easy, but certainly doable. I actually wanted to have a container built with _all_ nimble packages that was able to install. But the image grew fairly large and I'm not sure how it would impact run-times of code snippets. What I could do is add the logic required to pull in packages and create a file in the nim-playground repository (which is where this needs to be fixed) that lists packages to install. Then people could create PRs for the packages they want.

Another issue that arises with this though is how to deal with updates. When should packages update?

**Comment by juancarlospaco** [comment]
I dont think all packages tho, maybe from the Nim repo important_packages list.
:thinking:

**Comment by PMunch** [comment]
Starting with the important_packages list is definitely a good idea!

**Comment by PMunch** [comment]
This is now implemented, and the playground has a file that will be used to add packages that you can find here: https://github.com/PMunch/nim-playground/blob/master/docker/packages.nimble. If you want to add/remove a package simply create a PR to that repository.
